plugins:
  kajabi_sso_enabled:
    default: false
    client: true
  kajabi_client_id:
    default: ""
    client: false
    secret: true
  kajabi_client_secret:
    default: ""
    client: false
    secret: true

